spring.application.name: crypto-dashboard

price-monitor:
  api-uri: http://localhost:8888/api/v1/prices/{cryptoUnit}-USD/market-price

currency-monitor:
  api-uri: http://localhost:9999/api/v1/currencies/{currencyUnit}
